version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
      # Add any installation commands here if needed
  
  pre_build:
    commands:
      - echo "Pre-build phase"
      # Any commands to execute before the build (optional)

  build:
    commands:
      - echo "Build phase"
      - cd lamdba  # Replace with the path to your root directory
      - sh deploy.sh # This file is present in the lamdba folder, contains all the commands required for deployment

  post_build:
    commands:
      - echo "Post-build phase"
      # Any commands to execute after the build (optional)